version: '3'
services:
  vpn_proxy_wo:
    image: corykujawski/lethe
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 209.222.18.218
      - 209.222.18.222
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - REGION=US East
      - USERNAME=<username>
      - PASSWORD=<password>
      - LOCAL_NETWORK=10.1.1.0/24
    networks:
      - vpn_proxy_wo
    ports:
      - 8118:8118
    restart: always

networks:
  vpn_proxy_wo:
